// Constants used in models
const consts = {
  // Users: level
  USER_LEVEL_ADMIN: 1,
  USER_LEVEL_AGENT: 6,
  USER_LEVEL_KEEPER: 7,
  USER_LEVEL_ASSIGNER: 8,
  USER_LEVEL_TESTER: 9,
  USER_LEVEL_NORMAL: 20,
  USER_LEVEL_DISABLED: 30,
  USER_LEVEL_DELETED: 31,

  // History: type
  HISTORY_TYPE_ADD_FUNDS: 1,
  HISTORY_TYPE_BUY: 2,
  HISTORY_TYPE_REFUND: 3,

  // Orders: status
  ORDER_STATUS_UNCLAIMED: 1,
  ORDER_STATUS_CLAIMED: 2,
  ORDER_STATUS_REJECTED: 3,
  ORDER_STATUS_APPROVED: 4,
  ORDER_STATUS_CLOSED: 5,
  ORDER_STATUS_PAID: 6,
  ORDER_STATUS_PROCESSED: 7,
  ORDER_STATUS_SAMPLE_RECEIVED: 8,
  ORDER_STATUS_ASSIGNED: 9,
  ORDER_STATUS_TESTED: 10,
  ORDER_STATUS_REPORT_SHIPPED: 11,
  ORDER_STATUS_COMPLETED: 12,
  ORDER_STATUS_REFUNDED: 13,

  // orderImages: type
  ORDER_IMAGE_TYPE_CLIENT: 1,
  ORDER_IMAGE_TYPE_WAREHOUSE: 2,
  ORDER_IMAGE_TYPE_TEST: 3,

  // Recharges: method
  PAYMENT_METHOD_ALIPAY: 1,
  PAYMENT_METHOD_WECHAT: 2,
};

export default Object.freeze(consts);
